name: on_quran_uiux
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter  
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  lottie: ^2.1.0
  flutter_svg: ^1.1.6
  flutter_bloc: ^7.2.0
  hydrated_bloc: ^7.1.0
  animated_text_kit: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:  
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/lotties/
    
  fonts:
    - family: QuranFont
      fonts:
        - asset: assets/fonts/arabic/KFGQPC-Uthmanic-Script-HAFS-Regular.otf
    - family: ArabicCaligraphy
      fonts:
        - asset: assets/fonts/caligraph/aAwalRamadhan.otf
    - family: Roboto
      fonts:
        - asset: assets/fonts/ui/Roboto-Regular.ttf
  
  
  
  
  
  
  
  
