name: on_quran_uiux
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter  
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  lottie: ^2.1.0
  flutter_svg: ^1.1.6
  flutter_bloc: ^7.2.0
  hydrated_bloc: ^7.1.0
  animated_text_kit: ^4.2.2
  flutter_riverpod: ^2.3.6
  riverpod: ^2.3.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  onboarding: ^3.1.0
  badges: ^3.1.1
  intl: ^0.18.1
  hijriyah_indonesia: ^0.1.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.5

flutter:  
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/images/logo.png
    - assets/lotties/
    
  fonts:
    - family: QuranFont
      fonts:
        - asset: assets/fonts/arabic/KFGQPC-Uthmanic-Script-HAFS-Regular.otf
    - family: ArabicCaligraphy
      fonts:
        - asset: assets/fonts/caligraph/aAwalRamadhan.otf
    - family: Tajawal
      fonts:
        - asset: assets/fonts/ui/Tajawal-Regular.ttf
  
  
  
  
  
  
  
  
